// dia da semaana por numero (switch case)

var prompt = require('prompt-sync')();

let dia = Number(prompt("Digite o numero do dia da semana"));

switch(dia){
    case 1:
        console.log("Odia da semana eh domingo");

    case 2:
        console.log("Odia da semana eh segunda")

    case 3:
        console.log("Odia da semana eh terca")

    case 4:
        console.log("Odia da semana eh quarta")

    case 5:
        console.log("Odia da semana eh quinta")

    case 6:
        console.log("Odia da semana eh sexta")

    case 7:
        console.log("Odia da semana eh sabado")
}
//     case 1:
//         console.log("Odia da semana eh segunda")
// }